{% set name = "mvlearn" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neurodata/mvlearn/releases/download/{{ version }}-torch/{{ name }}-{{ version }}.tar.gz
  sha256: 6a95779b4695ef532ba256e93368dcb19f96556f189599a20a69e8a7dc4d4643

build:
  noarch: python
  number: 0
  script: 
    "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - graspy >=0.1.1
    - matplotlib-base >=3.0.0
    - numpy >=1.17.0
    - pandas >=0.25.0
    - scikit-learn >=0.19.1
    - scipy >=1.1.0
    - seaborn >=0.9.0
    - pytorch >=1.1.0
    - tqdm
    - joblib >= 0.11

test:
  imports:
    - mvlearn
    - mvlearn.factorization
    - mvlearn.cluster
    - mvlearn.cotraining
    - mvlearn.construct
    - mvlearn.datasets
    - mvlearn.embed
    - mvlearn.plotting
    - mvlearn.utils

about:
  home: https://mvlearn.neurodata.io/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'A python package for multi-view machine learning'
  description: |
    mvlearn is a python package for multi-view machine learning. It offers
    a comprehensive, tested, and well-documented collection of multi-view
    learning tools, enabling anyone to readily access and apply such
    methods to their data.
  doc_url: https://mvlearn.neurodata.io/
  dev_url: https://github.com/neurodata/mvlearn

extra:
  recipe-maintainers:
    - gmischl1
    - rflperry
