{% set name = "mvlearn" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mvlearn/mvlearn/releases/download/{{ version }}-conda/{{ name }}-{{ version }}.tar.gz
  sha256: 70ac4f459c9a2febfd0bfa8c918de80d9a7b6e194d539a7275a2ca880515c5f5

build:
  noarch: python
  number: 0
  script: 
    "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - graspy >=0.1.1
    - matplotlib-base >=3.0.0
    - numpy >=1.17.0
    - scikit-learn >=0.19.1
    - scipy >=1.4.0
    - seaborn >=0.9.0
    - pytorch >=1.1.0
    - tqdm
    - python-picard >=0.4
    - joblib >=0.11

test:
  imports:
    - mvlearn
    - mvlearn.cluster
    - mvlearn.compose
    - mvlearn.datasets
    - mvlearn.decomposition
    - mvlearn.embed
    - mvlearn.model_selection
    - mvlearn.plotting
    - mvlearn.semi_supervised
    - mvlearn.utils

about:
  home: https://mvlearn.github.io/
  license: MIT
  license_file: LICENSE
  summary: 'A python package for multiview machine learning'
  description: |
    mvlearn aims to serve as a community-driven open-source software package
    that offers reference implementations for algorithms and methods related
    to multiview learning (machine learning in settings where there are
    multiple incommensurate views or feature sets for each sample). It brings
    together the most widely-used tools in this setting with a standardized
    scikit-learn like API, well tested code and high-quality documentation.
    Doing so, we aim to facilitate application, extension, and comparison of
    methods, and offer a foundation for research into new multiview algorithms.
    We welcome new contributors and the addition of methods with proven
    efficacy and current use.
  doc_url: https://mvlearn.github.io/
  dev_url: https://github.com/mvlearn/mvlearn

extra:
  recipe-maintainers:
    - gavinmischler
    - rflperry
