{% set name = "mvlearn" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mvlearn/mvlearn/releases/download/{{ version }}-conda/{{ name }}-{{ version }}.tar.gz
  sha256: 4a4f835704abcc19602f4c71997daafd8a0440f12644bdcfe19064c5d67e4589

build:
  noarch: python
  number: 0
  script: 
    "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - graspy >=0.1.1
    - matplotlib-base >=3.0.0
    - numpy >=1.17.0
    - pandas >=0.25.0
    - scikit-learn >=0.19.1
    - scipy >=1.1.0
    - seaborn >=0.9.0
    - pytorch >=1.1.0
    - tqdm
    - python-picard >=0.4
    - joblib >=0.11

test:
  imports:
    - mvlearn
    - mvlearn.cluster
    - mvlearn.compose
    - mvlearn.datasets
    - mvlearn.decomposition
    - mvlearn.embed
    - mvlearn.model_selection
    - mvlearn.plotting
    - mvlearn.semi_supervised
    - mvlearn.utils

about:
  home: https://mvlearn.github.io/
  license: MIT
  license_file: LICENSE
  summary: 'A python package for multi-view machine learning'
  description: |
    mvlearn is a python package for multi-view machine learning. It offers
    a comprehensive, tested, and well-documented collection of multi-view
    learning tools, enabling anyone to readily access and apply such
    methods to their data.
  doc_url: https://mvlearn.github.io/
  dev_url: https://github.com/mvlearn/mvlearn

extra:
  recipe-maintainers:
    - gavinmischler
    - rflperry
